### ISSUE TITLE
Add possibility to mark text in order to copy/paste it elsewhere

### ISSUE THREAD

**Issue by loveisfoss** [Lugsole/net.lugsole.bible_gui#11]
As the title says, it would be nice to have the possibility to mark bible text in order to copy/paste it elsewhere.
A good example is when one wants to share a verse with someone.

**Comment by Lugsole** [comment]
In progress... I managed to break a thing while working on the next release.

**Comment by Lugsole** [comment]
The copy works now. It should be released soon.
