### ISSUE TITLE
update runtime

### ISSUE THREAD

**Issue by dln949** [Lugsole/net.lugsole.bible_gui#14]
I keep getting this message regarding the flatpak version of Bible:  "Info: org.gnome.Platform//44 is end-of-life, with reason:  The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform."  

Any ideas regarding how long it will take before flatpak Bible switches to a current runtime?

**Comment by Lugsole** [comment]
Just finished! The Bible app now uses 46.
