### ISSUE TITLE
Trouble importing different translations into Bible on Librem 5 linux mobile phone

### ISSUE THREAD

**Issue by bg314** [Lugsole/net.lugsole.bible_gui#5]
Using Bible v0.1.3 on the Librem 5 (Pureos Byzantium 5.18.0-1). The file browsing facility in the application cannot see the downloaded translation (NKJV.SQLite3) when I navigate to the folder /home/purism that contains the file (Any Bible Fomat selected, in Preferences). In fact, the application cannot seen any file at all when I choose "Any File" from the drop-down menu.

**Comment by Lugsole** [comment]
I believe I fixed this on the flathub app system. Let me know if the issue persists. I think I have a different issue to fix now relating to the file picker not knowing what to filter out and what to leave in the file picker.
