### ISSUE TITLE
Binary conflicts with CLI Bible program

### ISSUE THREAD

**Issue by kj7rrv** [Lugsole/net.lugsole.bible_gui#6]
There's a command-line Bible program called `bible-kjv` available in [Debian's
repositories](https://packages.debian.org/bullseye/bible-kjv) and the [Arch
User Repository](https://aur.archlinux.org/packages/bible-kjv), but it installs
its binary as `bible`, conflicting with this program. Is there any chance this
program's binary could be renamed to `bible_gui` or something like that to fix
the conflict? Since this is a GUI program that's normally launched from a
desktop entry, it shouldn't be a problem for users to have the binary's name
change.

**Comment by Lugsole** [comment]
In progress... next release.

**Comment by Lugsole** [comment]
The new updated version has a new app name. Solved.
