### ISSUE TITLE
Dark mode OS setting not respected

### ISSUE THREAD

**Issue by Psychpsyo** [Lugsole/net.lugsole.bible_gui#7]
The Bible seems to start in light mode and I can't find a way to change it to dark mode either.

OS: Linux Mint 21 Cinnamon (set to dark mode)

**Comment by Lugsole** [comment]
What I think the problem could be is that the theme is not installed on the flatpak system or the theme is not GTK4 comparable. Either way in GTK4 there is now a dark mode/light mode setting that can be toggled and in my rather limited testing the dark mode/light mode is respected on Gnome 42 and it toggles between dark and light Adwaita. Do you know if the theme you are using supports GTK4?

**Comment by TheEvilSkeleton** [comment]
This is a Cinnamon issue, as they don't properly support the dark style preference.
